name: curriculum-vitae
run-name: ${{ github.actor }} is building tex files.
on: [push, workflow_dispatch]
jobs:
  building-tex-files:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - uses: actions/checkout@v3
      - name: Finding TEX files to build
        run: echo "FILES=$(ls *.tex | grep -xv "m-cv.tex")" >> $GITHUB_ENV
      - name: Building PDFs
        run: ${{ env.FILES }} | xargs context
      - name: Committing and pushing PDFs
        run: |
          ${{ env.FILES}} | xargs git add
          git commit -m "Updated PDFs ${{ env.FILES }}"
          git push