name: curriculum-vitae
run-name: ${{ github.actor }} is building tex files.
on: [push, workflow_dispatch]
jobs:
  Compile-Actions:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build PDF
        run: ls *.tex | grep -xv "m-cv.tex" | xargs context
      - uses: stefanzweifel/git-auto-commit-action@v5
