name: curriculum-vitae
on: [push, workflow_dispatch]
jobs:
  building-tex-files:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v3
      - name: Building PDFs
        run: echo $(ls *.tex | grep -xv "m-cv.tex") | xargs context
      - name: Committing and pushing PDFs
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "Updated PDFs."
          git push