name: curriculum-vitae
run-name: ${{ github.actor }} is building tex files.
on: [push, workflow_dispatch]
jobs:
  building-tex-files:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    env:
      files: ls *.tex | grep -xv "m-cv.tex"
    steps:
      - uses: actions/checkout@v3
      - name: Build PDFs
        run: files | xargs context
      - name: Push PDFs
        run: |
          files | xargs git add
          git commit -m "Updated PDFs $file"