name: curriculum-vitae
on: [push, workflow_dispatch]
jobs:
  building-tex-files:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - uses: actions/checkout@v3
      - name: Building PDFs
        run: echo $(ls *.tex | grep -xv "m-cv.tex") | xargs context
      - name: Committing and pushing PDFs
        run: |
          git commit -am "Updated PDFs ${{ env.FILES }}"
          git push